Source/GMCAbilitySystem/Private/Ability/GMCAbility.cpp
Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h

Adds a function that the user can call in MovementUpdate/PredictionTick that will apply the corresponding tag to the ASC according to the value of the bool. Also fixed a bug where abilities wouldn't end even if there was a blocked tag or they were missing a needed tag. They wouldn't call begin but they wouldn't end or get gc'd either.

add matchtagtobool feature + fix abilities not ending after checking tags

---

Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
Source/GMCAbilitySystem/Public/Attributes/GMCAttributes.h
Source/GMCAbilitySystem/Public/Effects/GMCAbilityEffect.h

This is my initial stab at doing attribute modifiers.
The following modifiers exist:
```
Add
Multiply
Divide
```
The Attribute now keeps track of its BaseValue, an AdditiveMultiplier, a MultiplyModifier, and a DivideModifier. 
Additive Multiplier starts at 0, Multiply and Divide start at 1.
When you apply an Add effect, it just adds or subtracts from the Additive value.
For Multiply/Divide, the same is true. If you apply an effect with a Multiply type and a value of 1, it will add 1 to the MultiplyModifier. This would result in doubling the value. Which is weird if you don't know it, but I think it's the easiest way to add this.
The actual Value calc is done with:
```cpp
Value = (AdditiveModifier + (BaseValue * MultiplyModifier)) / DivideModifier;
```
(There are checks that happen before …

Adding Attribute Modifiers

---

GMCAbilitySystem.uplugin
Source/GMCAbilitySystem/Private/Debug/GameplayDebuggerCategory_GMCAbilitySystem.cpp
Source/GMCAbilitySystemTypesInclude/GMCAbilitySystemTypesInclude.Build.cs

There were a few warnings when compiling in Development mode (e.g. a missing directory that probably is a lingering artifact from earlier revisions), as well as a complete failure to compile under a Shipping configuration (due to it still trying to compile the gameplay debugger).
I cleaned these up in my own build, figured I should contribute the fixes back. :)

Main branch cleanup (macOS, Linux, 'Shipping' configuration)

---

GMCAbilitySystem.uplugin
Source/GMCAbilitySystem/Private/Ability/Tasks/WaitForGameplayTagChange.cpp
Source/GMCAbilitySystem/Private/Animation/GMCAbilityAnimInstance.cpp
Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
Source/GMCAbilitySystem/Private/Utility/GameplayElementMapping.cpp
Source/GMCAbilitySystem/Public/Ability/Tasks/WaitForGameplayTagChange.h
Source/GMCAbilitySystem/Public/Animation/GMCAbilityAnimInstance.h
Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h
Source/GMCAbilitySystem/Public/Utility/GameplayElementMapping.h
Source/GMCAbilitySystemEditor/GMCAbilitySystemEditor.Build.cs
Source/GMCAbilitySystemEditor/Private/GMCAbilitySystemEditor.cpp
Source/GMCAbilitySystemEditor/Private/Properties/GameplayElementMappingDetails.cpp
Source/GMCAbilitySystemEditor/Public/GMCAbilitySystemEditor.h
Source/GMCAbilitySystemEditor/Public/Properties/GameplayElementMappingDetails.h

This is an actual feature addition, separate from the cleanup PR, and adds several things:
* An `OnActiveTagsChanged` delegate, called when the active tags change at all.
* The ability to add targeted delegates, which will only be called when changes to tags match a specific filter.
* A `WaitForGameplayTagChange` ability task, powered by the above.
The second of those is also necessary to (properly) create a GMCAbilitySystem equivalent to GAS's ability to map tag filters to blueprint properties and have them automatically updated, which is kinda useful in general and _very_ useful in animation blueprints specifically.

Tag Change Delegates

---

GMCAbilitySystem.uplugin
Source/GMCAbilitySystem/Private/Animation/GMCAbilityAnimInstance.cpp
Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
Source/GMCAbilitySystem/Private/Utility/GameplayElementMapping.cpp
Source/GMCAbilitySystem/Public/Animation/GMCAbilityAnimInstance.h
Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h
Source/GMCAbilitySystem/Public/Utility/GameplayElementMapping.h

If a property binding has a single tag (rather than multiple), it will also be considered valid for any attribute changes which match that tag.
* Boolean properties will be set as (value > 0)
* Int properties will be set as the rounded attribute value.
* Float and Double properties will be set as the attribute value.
Also changes the plugin category to "GMC", where GMCExtended is going to live as well, so that extension plugins get grouped together nicely in the plugin manager. :)

Add the ability to map attributes to properties as well as tags.

---

Source/GMCAbilitySystem/Private/Animation/GMCAbilityAnimInstance.cpp
Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
Source/GMCAbilitySystem/Private/Utility/GameplayElementMapping.cpp
Source/GMCAbilitySystem/Public/Animation/GMCAbilityAnimInstance.h

This addresses #38 -- I had fixed it in my game-specific fork of GMAS a while ago, and forgot to merge it over to normal dev.

Guard against uninitialized attributes.

---

Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h

This now has:
* `HasTag` (single gameplay tag)
* `HasTagExact` (single gameplay tag, exact match)
* `HasAnyTag` (gameplay tag container)
* `HasAnyTagExact` (gameplay tag container, exact match)
* `HasAllTags` (gameplay tag container)
* `HasAllTagsExact` (gameplay tag container, exact match)
In addition, I took the opportunity to change most of our gameplay tag parameters to const pass-by-reference where viable, just so we're not creating extra copies needlessly.

Add extra accessors for active tags

---

Source/GMCAbilitySystem/Private/Animation/GMCAbilityAnimInstance.cpp
Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
Source/GMCAbilitySystem/Private/Debug/GameplayDebuggerCategory_GMCAbilitySystem.cpp
Source/GMCAbilitySystem/Public/Animation/GMCAbilityAnimInstance.h
Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h

Just getting rid of our old no-longer-needed custom binding for structs -- we can just call it in GMC directly -- and adding some error-checking to the debugger category.

Minor cleanup/safety checks.

---

Source/GMCAbilitySystem/Private/Actors/GMAS_Pawn.cpp
Source/GMCAbilitySystem/Private/Animation/GMCAbilityAnimInstance.cpp
Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
Source/GMCAbilitySystem/Private/Debug/GameplayDebuggerCategory_GMCAbilitySystem.cpp
Source/GMCAbilitySystem/Private/Utility/GMASUtilities.cpp
Source/GMCAbilitySystem/Private/Utility/GameplayElementMapping.cpp
Source/GMCAbilitySystem/Public/Actors/GMAS_Pawn.h
Source/GMCAbilitySystem/Public/Animation/GMCAbilityAnimInstance.h
Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h
Source/GMCAbilitySystem/Public/Utility/GMASUtilities.h
Source/GMCAbilitySystem/Public/Utility/GameplayElementMapping.h

This will:
* Cleanly handle the scenario where the preview pawn is lacking an ability system component, e.g. was set up in blueprint.
* Adds a GMAS_Pawn convenience class -- totally optional -- which sets up the capsule, mesh, camera, and an ability component. It also will automatically add the input mapping context for you if you set one in the defaults.
(I also cleaned up a bunch of the function/property categories, because it was driving me a tiny bit nuts.)
This branches off the rest of the dev branch cleanups, so apply that PR first (or delete it if doing this one first).

Additional animation utility functionality

---

Source/GMCAbilitySystem/GMCAbilitySystem.Build.cs
Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
Source/GMCAbilitySystem/Public/Attributes/GMCAttributes.h

This changes `FGMCAttributeSet` to utilize the "fast net array serialization." The long and short of it is that now attributes should only send changes to their values, not the entire attribute set.
(Yay! Efficiency!)

Change attributes to use net deltas.

---

Source/GMCAbilitySystem/GMCAbilitySystem.Build.cs
Source/GMCAbilitySystem/Private/Attributes/GMCAttributeClamp.cpp
Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
Source/GMCAbilitySystem/Private/Effects/GMCAbilityEffect.cpp
Source/GMCAbilitySystem/Public/Attributes/GMCAttributeClamp.h
Source/GMCAbilitySystem/Public/Attributes/GMCAttributeModifier.h
Source/GMCAbilitySystem/Public/Attributes/GMCAttributes.h
Source/GMCAbilitySystem/Public/Attributes/GMCAttributesData.h
Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h
Source/GMCAbilitySystem/Public/Effects/GMCAbilityEffect.h

Core Change:
AttributeModifiers now have a `bApplyToBaseValue` flag:
```
// Only affects Add modifiers
// Should this value directly modify the Attribute's BaseValue
// Set True for temporary effects, False for permanent effects
```
Applying to base value will directly modify the base value (duh :D). Otherwise it will use the Additive Modifier like how the old version does. For temporary effects, the effect will be (likely) be negated when the effect ends, or at some other point. For these kinds of effects, the total modifier is needed, as when the effect negates, it will subtract that value. This mostly matters when clamping (also in this PR).
--------
Some Examples of this in action:
CurrentAttributeValue: 100 (+0 Add modifier)
CurrentAttribute Value gets clamped to [0, 300]. 
Effect …

Attribute refactor

---

Source/GMCAbilitySystem/Private/Ability/GMCAbility.cpp
Source/GMCAbilitySystem/Private/Ability/Tasks/GMCAbilityTaskBase.cpp
Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
Source/GMCAbilitySystem/Public/Ability/GMCAbility.h
Source/GMCAbilitySystem/Public/Ability/Tasks/GMCAbilityTaskBase.h
Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h

Basically I've moved the tick execution for effects and cooldowns to ancillary tick. I've also added the option for abilities to be activated on ancillary tick as well as a new tick event for abilities. Tasks are also given a new function that will tick from ancillary tick.

move effect and cooldowns to ancillary tick, add ancillary tick options for abilities and tasks

---

Source/GMCAbilitySystem/GMCAbilitySystem.Build.cs
Source/GMCAbilitySystem/Private/Attributes/GMCAttributeClamp.cpp
Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
Source/GMCAbilitySystem/Public/Attributes/GMCAttributeClamp.h
Source/GMCAbilitySystem/Public/Attributes/GMCAttributes.h
Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h
Source/GMCAbilitySystem/Public/Effects/GMCAbilityEffect.h

This PR alters attributes to be replicated more conservatively, so we're not just replicating the entire collection of attributes all at once.
* `FAttribute` now inherits `FFastArrayItem`.
* `FUnboundAttributeSet` now inherits `FFastArraySerializer` and thus will use delta updates to replicate attributes.
* The above change means that unbound attributes are _not_ created except on the authority, otherwise they get doubled on the first update from an `FFastArraySerializer`.
* `BoundAttributes` is no longer an instanced struct; it instead binds to the `Value`, `BaseValue`, and modifiers for each bound attribute, allowing those float values to be independently updated.
* Bound attributes are now sorted by attribute tag when instanciated, ensuring a consistent order for them for purposes of …

Attribute Replication Cleanup

---

Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
Source/GMCAbilitySystem/Public/Ability/GMCAbility.h
Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h

This adds functions to:
* Count the number of queued abilities matching a tag.
* Count the number of active abilities matching a tag or class.
This also adds a `bAllowMultipleInstances` setting to the base `GMCAbility`; if false, if an instance of the class is already active it will return false when calling `TryActivateAbility`.

Ensure abilities can be unique (one instance at a time).

---

Source/GMCAbilitySystem/Private/Ability/GMCAbility.cpp
Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
Source/GMCAbilitySystem/Public/Ability/GMCAbility.h
Source/GMCAbilitySystem/Public/Ability/GMCAbilityData.h
Source/GMCAbilitySystem/Public/Ability/GMCAbilityMapData.h
Source/GMCAbilitySystem/Public/Ability/Tasks/SetTargetDataFloat.h
Source/GMCAbilitySystem/Public/Ability/Tasks/SetTargetDataGameplayTag.h
Source/GMCAbilitySystem/Public/Ability/Tasks/SetTargetDataInt.h
Source/GMCAbilitySystem/Public/Ability/Tasks/SetTargetDataVector3.h
Source/GMCAbilitySystem/Public/Attributes/GMCAttributeClamp.h
Source/GMCAbilitySystem/Public/Attributes/GMCAttributeModifier.h
Source/GMCAbilitySystem/Public/Attributes/GMCAttributes.h
Source/GMCAbilitySystem/Public/Attributes/GMCAttributesData.h
Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h
Source/GMCAbilitySystem/Public/Effects/GMCAbilityEffect.h
Source/GMCAbilitySystem/Public/Utility/GameplayElementMapping.h

- Adding Proper UPROPERTY Categories, this ensure the plugin is able to compile from source engine build (Please, don't forgot to add them in your UPROPERTY).
- Change in the `EndAbility` flow : 
- Task termination and state is now done is an private method (`FinishEndAbility`)
- Adding `CancelAbility`, purpose is the same of `EndAbility` at the difference it doesn't trigger `EndAbilityEvent`
- The choice of splitting function is to ensure a better understand for end user on blueprint side (GAS Like)
- Check as `TagRequirements `are now done in `TryActivateAbility`, before the instanciation from the CDO.
- Adding `PreExecuteCheckEvent()` to allow end user to execute basic logic test like variable sanity check, and avoid ability execution if they fail (post instantiation)
- Adding Helpers …

Ability Precheck, Abilities Cancel by Tag, Check Before instances, Engine Plugin Compability

---

Source/GMCAbilitySystem/Private/Ability/Tasks/WaitForInputKeyPress.cpp
Source/GMCAbilitySystem/Private/Ability/Tasks/WaitForInputKeyRelease.cpp
Source/GMCAbilitySystem/Public/Ability/GMCAbility.h
Source/GMCAbilitySystem/Public/Ability/Tasks/WaitForInputKeyPress.h
Source/GMCAbilitySystem/Public/Ability/Tasks/WaitForInputKeyRelease.h

- Added `UGMCAbilityTask_WaitForInputKeyPress` which will wait for the ability's input action to be triggered to complete the task.
- Fixed `UGMCAbilityTask_WaitForInputKeyRelease` keeping a pointer to an element of the input component's action bindings array. In (semi-rare) cases, this pointer would end up pointing to wrong/invalid data and cause the task to never complete.

Add UGMCAbilityTask_WaitForInputKeyPress, fix some pointer misuse in UGMCAbilityTask_WaitForInputKeyRelease

---

Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h

It's useful to have custom logic for checking tag requirements. For example Lyra uses the ULyraAbilityTagRelationshipMapping to describe tag relationships in a "central" data asset, rather than managing across individual abilities. See https://github.com/EpicGames/UnrealEngine/blob/release/Samples/Games/Lyra/Source/LyraGame/AbilitySystem/Abilities/LyraGameplayAbility.cpp#L315
This change would allow users to implement something like this.

Allow CheckActivationTags() to be overridden

---

Source/GMCAbilitySystem/Private/Animation/GMCAbilityAnimInstance.cpp
Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
Source/GMCAbilitySystem/Private/Utility/GameplayElementMapping.cpp
Source/GMCAbilitySystem/Public/Animation/GMCAbilityAnimInstance.h
Source/GMCAbilitySystem/Public/Utility/GameplayElementMapping.h

* Ensure clean setup of unbound attributes in all scenarios.
* Ensure attribute changes only generate callbacks if the value actually changed.
* Handle the GMAS animation blueprint base being used as a child layer as well.

Minor Cleanup

---

Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp
Source/GMCAbilitySystem/Public/Components/GMCAbilityComponent.h

These methods are useful during character initialization as a way to support customization of starting effects at runtime. I'm specifically using this to support module game features which can add/remove effects depending on which game features are loaded.

Add methods to add/remove starting effects

---

Source/GMCAbilitySystem/Public/Effects/GMCAbilityEffect.h

This PR updates the AbilityEffect lifecycle functions to be overridable. It also moves some of the private members to protected so that they can be accessed by subclasses.

Virtualize ability effect

---

Source/GMCAbilitySystem/Private/Components/GMCAbilityComponent.cpp

A superfluous call to MarkArrayDirty() is made when building UnboundAttributes. We already call to "MarkItemDirty" which makes a call to "MarkArrayDirty" for us.
```cpp
void MarkItemDirty(FFastArraySerializerItem & Item)
{
if (Item.ReplicationID == INDEX_NONE)
{
Item.ReplicationID = ++IDCounter;
if (IDCounter == INDEX_NONE)
{
IDCounter++;
}
}
Item.ReplicationKey++;
MarkArrayDirty();
}
```
For some reason I cannot explain, this causes issues in certain cases. The Array Replication indexes get all out of whack, and the server is unable to replicate down to the client.

Fix Extra MarkArrayDirty() Call
